### PR TITLE
Add gulp test task

### PR DESCRIPTION
**Pull request by jfmercer**
### Description
- Most importantly, `gulp test` now runs those ES6 jasmine specs.
- Switches default task from `serve` to `build` and `test`
- Removes `karma`
- Removes `test.html`
- Updates test instructions in `README`
- Adds `test` to `package.json` scripts
- Per jspm docs, adds jspm as npm devDependency
- Travis now runs npm & jspm locally, not globally
- **TODO**: setup PhantomJS testing
  - Currently, the parsers and validators are tested
  - _BUT_ the UI code is **NOT** tested
  - We must add UI code testing at some point.
### Test
- If the build passes, it's good to merge.

### CODE REVIEW

**Comment by jfmercer** [comment]
@nateabele I noticed that you [deleted `src/config.js`](https://github.com/radify/PR.js/commit/cfc1135fcd2dbc8402deab17eabd61b720c60472) from PR.js. Can `jspm` work without a `config.js`? Without it, `jspm install` fails, but if I use `jspm install -y`, it not only installs the jspm packages, but it also creates a new `config.js`. What's going on?

FWIW, this doesn't affect `gulp test`. The tests run and pass with or without `jspm install`.

For the time being, I removed `jspm install` from the Travis script so that it passes. But I can't help but think `jspm` should be included in Travis.

**Comment by nateabele** [comment]
> I noticed that you deleted src/config.js from PR.js.

That was inadvertent. I think I meant to move it to the repo root.

> But I can't help but think jspm should be included in Travis.

Yes, it should.

**Comment by jfmercer** [comment]
Well, how does this sound?

(1) I'll generate a `config.js` & commit it.
(2) I'll put `jspm install` back into Travis.

**Comment by nateabele** [comment]
Well, that would break the app. Currently there are only tests against the parsers and validators, not the UI code, which is why the tests still pass without installing JSPM packages. You can just put back the one I had (save for the `jasmine` references, which were only for `test.html`).

**Comment by jfmercer** [comment]
OK, this is good to merge.

**Comment by jfmercer** [comment]
The commit history is much longer & messier than I'd like. I'm going to create a new epic branch (`gulp-novicepiece`) and cherry-pick the important commits onto it.

**Pull request closed without merging**
