### PR TITLE
npm and jspm package updates

### PR DESCRIPTION
**Pull request by jfmercer**
### Description
- Packages updates.
### Test
1. Clone a clean PR.js repo
2. Checkout branch `jspm-package-updates`
3. Follow [the installation instructions](https://github.com/radify/PR.js#get-going)
4. After running `gulp serve`, 
   - open [`http://localhost:3003`](http://localhost:3003)
   - **Assert that** the app loads properly in the browser
5. In the search box, enter "radify"
   - **Assert that** Radify's public repos display in the left hand column
6. Click on `angular-model`
   - **Assert that** one or more PRs load.
7. Click on `#22Revert should remove new properties`
   - **Assert that** you see Wolan
   - **Assert that** you see the complete PR message.
   - **Assert that** you see a mix of red and green test results
8. Click on `View`
   - **Assert that** it takes you to [the PR request on Github](https://github.com/radify/angular-model/pull/22)

### CODE REVIEW

**Comment by gavD** [comment]
needs rebasing

**Comment by jfmercer** [comment]
Rebase complete.

**Comment by gavD** [comment]
Looks OK to me - I'll leave this to @nateabele to merge

**Comment by jfmercer** [comment]
I need to remove a couple of files which I committed by accident. I've marked it as NOMERGE until I've finished.

**Comment by jfmercer** [comment]
OK, it's ready now. 

One question for @nateabele: should `build.min.js` and `build.min.js.map` be added to the `.gitignore`? I seems to me that those files should be generated by a build command, rather than committed to the repo. Thoughts?

**Comment by jfmercer** [comment]
@nateabele Is this PR dead? Should I close it?

**Comment by nateabele** [comment]
Sorry, forgot to follow up. I remember I had some issues with it but they must have been rebased away or something.

> [S]hould build.min.js and build.min.js.map be added to the .gitignore?

If you want to do that, that's fine, but then you'll need to merge those changes to `gh-pages` and then commit the inverse of those changes over top of it, because that's the production build.

**Comment by jfmercer** [comment]
Hmm. I want to leave `gh-pages` alone until everything else gets sorted
out. I'll pass on the `gh-pages` update for now.

--jm

## 

John Mercer  |  Software Developer; Radify, Inc.  |  1-949-606-5003

**Pull request merged**
